### ISSUE TITLE
this script doesn't open zoom.exe automatically

### ISSUE THREAD

**Issue by fish1968** [simula67/meeting-auto-attender#2]
Hey, thanks for your script! I love it, however, it fails to run on my windows without changing.

I think you may forget to open the zoom exe file, before starting to join a meeting. Here is my modification
```python
def join_meeting_with_id(self, meeting_id, meeting_password): 
     .... codes omit ....
    # Open zoom app
    from os import system
    system(self.bin_path)
    logging.info(f"open {self.bin_path}")
    # locating the Zoom app
    ... codes omit ....
```

**Comment by simula67** [comment]
Hi @fish1968, you are welcome. I tend to use the join with meeting link option usually since it is more reliable and I haven't tested this branch of the code in a long time. Do you want to submit a pull request? I can merge it in.

**Comment by simula67** [comment]
Closed due to inactivity
